//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity_Assitance
    {
        public int idActivityAssistance { get; set; }
        public int idActivity { get; set; }
        public int idAssistance { get; set; }
        public System.DateTime start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public decimal kcal { get; set; }
        public string timeOcurred { get; set; }
        public bool status { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Assistance Assistance { get; set; }
    }
}
