//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.Publication_Activity = new HashSet<Publication_Activity>();
        }
    
        public int idPublication { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime time { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public int idUser { get; set; }
        public int likes { get; set; }
        public int disLikes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication_Activity> Publication_Activity { get; set; }
        public virtual User User { get; set; }
    }
}
