//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publication()
        {
            this.Publication_Activity = new HashSet<Publication_Activity>();
        }
    
        public int idPublication { get; set; }
        public System.DateTime datetime { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string type { get; set; }
        public int idUser { get; set; }
        public int likes { get; set; }
        public int disLikes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication_Activity> Publication_Activity { get; set; }
        public virtual User User { get; set; }
    }
}
