//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDataHistory
    {
        public int idUserHistory { get; set; }
        public decimal weight { get; set; }
        public decimal heigth { get; set; }
        public System.DateTime date { get; set; }
        public int idUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
