//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDataHistory
    {
        public int idUserHistory { get; set; }
        public decimal weight { get; set; }
        public decimal heigth { get; set; }
        public System.DateTime date { get; set; }
        public int idUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
